### ISSUE TITLE
support "content" in ssl map

### ISSUE THREAD

**Issue by yoshikakbudto** [Oefenweb/ansible-haproxy#139]
Use case:
We store all of our secrets in Hashicorp Vault. And that is true for the SSL pem
It would be nice to support a content parameter in `ansible.builtin.copy` for the construction like this one:

```yml
---
haproxy_ssl_map:
  - content: "{{ lookup('hashi_vault', 'secret=..... }}"
    dest: /etc/ssl/private/mysite.pem
```
