### ISSUE TITLE
Adding GZIP compression

### ISSUE THREAD

**Issue by DnR-iData** [Oefenweb/ansible-haproxy#48]
Hi,

I would like to know if it's possible to add the "gzip compression" support in the config file, please :

```conf
listen ft_web
 option http-server-close
 mode http
 bind 127.0.0.1:8090 name http
 default_backend bk_web
 
backend bk_web
 option http-server-close
 mode http
 compression algo gzip
 compression type text/html text/plain text/css
 server localhost 127.0.0.1:80
```

[http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4.2-compression%20alg](http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4.2-compression%20alg)

[https://www.haproxy.com/blog/haproxy-and-gzip-compression/](https://www.haproxy.com/blog/haproxy-and-gzip-compression/)

I don't know if there is another possibility, I've didn't see it in the documentation.

I think to add in `templates/etc/haproxy/backend.cfg.j2` something like this :

```jinja
{% for compression in backend.compression | default([]) %}
  compression {{ compression.key }} {{ compression.value }}
{% endfor %}
```

```yaml
    haproxy_backend:
      - name: my_back
        description: Back-end for my back
        mode: http
        balance: roundrobin
        option:
          - http-keep-alive
        compression:
          - algo: gzip
          - type: text/html text/plain text/css
        server:
          - name: my back
            listen: "my-back:80"
            param:
              - check
```

Thank you
